name: py
    
on:
  push:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
<<<<<<< HEAD
=======
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duolingo-api
>>>>>>> 044357c2f9efa28b442fd8362e2bdb07bc351e28

      - name: execute py script # run the run.py to get the latest data
        run: |
          python duolingoApi.py
          
      - name: commit files
        run: |
          git config --local user.email "jnacorda04@gmail.com"
          git config --local user.name "Jomar77"
          git add -A
          git commit -m "update data" -a
